use crate::parser::{Message, TestCase, UserContent};

/// Render the agent-facing version of a test case.
///
/// Strips all HTML comments and returns only the plain text user messages
/// that should be sent to the agent.
///
/// For `UserContent::Guidance`, returns an empty string since the actual
/// message needs to be generated by an LLM.
pub fn render_agent_input(test_case: &TestCase) -> Vec<String> {
    test_case
        .messages
        .iter()
        .filter_map(|msg| match msg {
            Message::User(UserContent::PlainText(text)) => Some(text.clone()),
            Message::User(UserContent::Guidance(_)) => None, // Must be generated
            Message::Assistant { .. } => None,              // Not sent to agent
        })
        .collect()
}

/// Render the evaluation version of a test case.
///
/// Returns all assertion comments (assistant messages + user guidance + storyline)
/// for evaluation by an LLM judge.
pub fn render_evaluations(test_case: &TestCase) -> Vec<Evaluation> {
    let mut evaluations = Vec::new();

    // Storyline assertions
    for comment in &test_case.storyline {
        evaluations.push(Evaluation {
            scope: EvaluationScope::Storyline,
            assertion: comment.clone(),
        });
    }

    // Per-message assertions
    for (i, msg) in test_case.messages.iter().enumerate() {
        match msg {
            Message::User(UserContent::Guidance(guidance)) => {
                for g in guidance {
                    evaluations.push(Evaluation {
                        scope: EvaluationScope::UserMessage(i),
                        assertion: g.clone(),
                    });
                }
            }
            Message::Assistant { assertions, .. } => {
                for c in assertions {
                    evaluations.push(Evaluation {
                        scope: EvaluationScope::AssistantMessage(i),
                        assertion: c.clone(),
                    });
                }
            }
            _ => {}
        }
    }

    evaluations
}

/// An evaluation assertion with its scope.
#[derive(Debug, Clone, PartialEq)]
pub struct Evaluation {
    pub scope: EvaluationScope,
    pub assertion: String,
}

/// The scope of an evaluation assertion.
#[derive(Debug, Clone, PartialEq)]
pub enum EvaluationScope {
    /// Applies to the entire conversation.
    Storyline,
    /// Applies to a specific user message (by index).
    UserMessage(usize),
    /// Applies to a specific assistant message (by index).
    AssistantMessage(usize),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn test_render_agent_input() {
        let content = r##"## Storyline
<!-- Test -->

## User Message
Hello

## Assistant Message
<!-- Should greet -->

## User Message
<!-- Generate a question -->

## Assistant Message
<!-- Should answer -->
"##;

        let case = parser::parse(content, "test").unwrap();
        let inputs = render_agent_input(&case);
        assert_eq!(inputs.len(), 1);
        assert_eq!(inputs[0], "Hello");
    }

    #[test]
    fn test_render_evaluations() {
        let content = r##"## Storyline
<!-- Overall test -->

## User Message
Hello

## Assistant Message
<!-- Should greet -->

## User Message
<!-- Generate question -->

## Assistant Message
<!-- Should answer -->
"##;

        let case = parser::parse(content, "test").unwrap();
        let evals = render_evaluations(&case);

        // Storyline + 1 assistant + 1 user guidance + 1 assistant = 4
        assert_eq!(evals.len(), 4);

        assert!(matches!(&evals[0],
            Evaluation {
                scope: EvaluationScope::Storyline,
                assertion,
            } if assertion == "Overall test"
        ));
    }
}
